server {
  listen 80;
  server_tokens off;
  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options DENY;

  root /usr/share/nginx/html;
  index index.html;

  # Re-resolve DNS Docker -> load balancing otomatis saat backend di-scale
  resolver 127.0.0.11 valid=5s;
  set $backend http://backend:3000;

  location /api/ {
    proxy_pass $backend;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location /metrics { return 404; }   # metrics tidak dibuka ke publik
}
